name: SpeedWerks Studio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.36595
title: SpeedWerks Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#33ace0'
    - '#0080ff'
    - '#0000ff'
    - '#00ffff'
    - '#000000'
  brandStrength: 0.5
  lightness: 0.1875
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
